# Generated by Django 3.2.5 on 2021-07-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=80)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
