# Generated by Django 3.2.4 on 2021-07-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='city',
            field=models.CharField(max_length=40),
        ),
    ]
